### ISSUE TITLE
RuntimeError: storage has wrong size: expected 1152921504606846976 got 16

### ISSUE THREAD

**Issue by yxxxxxxxx** [proteus1991/GridDehazeNet#1]
Hello, I am using your testing code but meet the following error:
'Traceback (most recent call last):
  File "test.py", line 71, in <module>
    net.load_state_dict(torch.load('{}_haze_best_{}_{}'.format(category, network_height, network_width)))
  File "/home/.local/lib/python3.7/site-packages/torch/serialization.py", line 387, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/home/.local/lib/python3.7/site-packages/torch/serialization.py", line 581, in _load
    deserialized_objects[key]._set_from_file(f, offset, f_should_read_directly)
RuntimeError: storage has wrong size: expected 1152921504606846976 got 16'
My pytorch version is 1.1.0 so I wonder if you met the same error? Thank you!

**Comment by proteus1991** [comment]
Hello, I didn't have this error when I tested my code. Please provide me more detailed information about this error (such as error log). Moreover, please check the weight name when you load it, I think this name shown in your error message as '{}haze_best{}_{}' is not correct. Thanks!

**Comment by yxxxxxxxx** [comment]
> Hello, I didn't have this error when I tested my code. Please provide me more detailed information about this error (such as error log). Moreover, please check the weight name when you load it, I think this name shown in your error message as '{}haze_best{}_{}' is not correct. Thanks!
![image](https://user-images.githubusercontent.com/26196715/62596686-d164b280-b915-11e9-83a1-11d60d120fb6.png)
@proteus1991 The model path is correct and this model 'outdoor_haze_best_3_6' in your repo is about 3.8M in my downloads project, thank you very much.

**Comment by proteus1991** [comment]
Hi, I think the weight you downloaded is corrupted. Please check this [Issue #12042](https://github.com/pytorch/pytorch/issues/12042), and consider to re-download this repo. If it is still not working, let me know.

**Comment by proteus1991** [comment]
This issue is closed. Reopen if necessary.
