### ISSUE TITLE
Perceptual loss network

### ISSUE THREAD

**Issue by world2025** [proteus1991/GridDehazeNet#12]
感谢你的分享，请我我可以在Perceptual loss network里将vgg16模型换成resnet?

**Comment by proteus1991** [comment]
可以的,任何backbone其实都可以用来作为perceptual loss的supervision.

**Comment by world2025** [comment]
好的，谢谢

**Comment by world2025** [comment]
还有一个问题就是，代码模块中是如何体现Feature Fusion with Channel-Wise Attention的？可以简单的解答一下吗？谢谢！

**Comment by proteus1991** [comment]
@tkone2018 请看一下对应的文章吧, 写的很详细了.

**Comment by world2025** [comment]
好的

**Comment by tkone2018** [comment]
@proteus1991 ,你好，我在训练outdoor数据集的时候出现gt的channel维度为4，然后就报错了，你之前有遇到这样的情况吗？

**Comment by tkone2018** [comment]
gt.shape torch.Size([4, 240, 240])

**Comment by proteus1991** [comment]
那是因为有些图是rgba格式,所以需要转换成rgb. 请在issue里面提问吧, 这样大家都能看到.

谢谢,

Xiaohong

**Comment by world2025** [comment]
@proteus1991 我昨天自己改好了，我就给撤销了，我下次碰到问题我就单独写出来哈
