### ISSUE TITLE
Outdoors dataset

### ISSUE THREAD

**Issue by yarqian** [proteus1991/GridDehazeNet#13]
I am sorry to ask that many images in the outdoors dataset are invalid. How did you do to solve this problem? By just removing the images from the traininglist? Thank you

**Comment by tkone2018** [comment]
@yarqian ok, i met the problem too. did you solve it ? thanks

**Comment by proteus1991** [comment]
Hi, when I downloaded the RESIDE dataset, all data is valid so I don't need to remove any image.

**Comment by world2025** [comment]
@proteus1991 可能是因为数据集更新还是没下全原因呢，我也遇到了这个问题，然后我就重新生成了一个trainlist，如果是我数据集没下全的原因的话我就得重新下了

**Comment by proteus1991** [comment]
@tkone2018 可能是因为数据集更新了，trainlist.txt 的图片有些可能访问不到了。用最新的RESIDE重新生成下这个txt就能解决这个问题了。
