### ISSUE TITLE
the effect is very different

### ISSUE THREAD

**Issue by shenhongqian-123456** [proteus1991/GridDehazeNet#17]
Hello, I train the network on my server according to your training method, the effect is very different, PSNR = 17.74, SSIM = 0.7954. What is the reason for this

**Comment by proteus1991** [comment]
Hi,

I need more information to help you. For example, which training data  are you using? How many epoches have you trained?

Thanks,

Xiaohong

**Comment by shenhongqian-123456** [comment]
Hello, Thank you for taking the time to answer my questions
         according to your paper, the results I ran out are PSNR =24.96 and SSIM =0.9266, which are quite different from the results in your paper.Set the following
              Learning_rate: 0.001
              crop_size: [240, 240]
               train_batch_size: 24
               val_batch_size: 1
               network_height: 3
              network_width: 6
              num_dense_layer: 4
             growth_rate: 16
             Lambda_loss: 0.04
             category: indoor
1399 images in ITS were selected from the indoor training data set

**Comment by proteus1991** [comment]
Hi, sorry for the late reply. I'm very busy recently. Have you solved this problem by retraining from scratch?

**Comment by shenhongqian-123456** [comment]
Thanks for your reply.I had solved this problem.Thanks very much.



---Original---

**Comment by gfgc522** [comment]
@shenhongqian-123456 Hello, I have the same problem as you, can you tell me how to solve it？Thanks.

**Comment by ghost** [comment]
@shenhongqian-123456 Would you please share with us how you solved it? thanks

**Comment by ghost** [comment]
@gfgc522 Hi, were you able to solve it? thanks!

**Comment by shenhongqian-123456** [comment]
Sorry, I'm a little busy recently. I mainly modified the format of the dataset，The main task is to modify the address information of the dataset, delete the original model of the author, and train again




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "proteus1991/GridDehazeNet"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月21日(星期一) 下午5:00
收件人:&nbsp;"proteus1991/GridDehazeNet"<GridDehazeNet@noreply.github.com&gt;;
抄送:&nbsp;"燕山大学-申红倩"<1473954947@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [proteus1991/GridDehazeNet] the effect is very different (#17)





 
@gfgc522 Hi, were you able to solve it? thanks!
