### ISSUE TITLE
The file described in the train/outdoor/trainlist.txt  cannot be located in the RESIDE_OTS_BETA?

### ISSUE THREAD

**Issue by Heibaizhu** [proteus1991/GridDehazeNet#18]
Thank you for your wonderful work !
However, I found the data file described in the train/outdoor/trainlist.txt  cannot be located in the RESIDE_OTS_BETA.  For example, the first item in the trainlist.txt is  "0005_0.8_0.04.jpg" while the item with minmal index in RESIDE_OTS_BETA is "0025_0.8_0.04.jpg".  The others  don't match neither. Is it possible that you put the wrong text file here accidentally ? 
I'm looking forward to your reply!

**Comment by proteus1991** [comment]
Hi, it looks like the RESIDE dataset has been updated. The trainlist.txt might be outdated.
