### ISSUE TITLE
Why did you use the Image.convert('RGB') when you read png format gt imgs?

### ISSUE THREAD

**Issue by Ikhwansong** [proteus1991/GridDehazeNet#19]
Why did you use the Image.convert('RGB') when you read png format gt imgs in the train_data.py?

![image](https://user-images.githubusercontent.com/39337513/109299317-412fea80-7878-11eb-89e2-84d96b1ee097.png)

**Comment by proteus1991** [comment]
To avoid the case where the image has 4 channels and in RGBA format.

**Comment by Ikhwansong** [comment]
Thanks!
