### ISSUE TITLE
why do u use pretrained best network weight to retrain the network?

### ISSUE THREAD

**Issue by leochangzliao** [proteus1991/GridDehazeNet#2]
As the title mentions, the code ([https://github.com/proteus1991/GridDehazeNet/blob/master/train.py#L98](url)) use the best weight (indoor_haze_best_3_6) to retrain the network with indoor training dataset. It seems  that it is not reasonable.

**Comment by proteus1991** [comment]
Hi, this is just an example to show how to retrain/finetune the GridDehazeNet. You can modify the code accordingly to match your use case.

**Comment by leochangzliao** [comment]
If I want to reproduce the experiment results,  I should comment the line mentioned above, is that right? @proteus1991

**Comment by leochangzliao** [comment]
After reading your [paper](https://xiaohongliu.ca/GridDehazeNet/resource/GridDehazeNet.pdf), I have some questions. 
1. Do u just use the ITS dataset to train the network and test on SOTS? 
2. Do u just use the OTS dataset to train the network and test on SOTS? 
3. If I use pretrained network (using OTS to train) to finetune on ITS, will I get better test results on SOTS?

**Comment by proteus1991** [comment]
> If I want to reproduce the experiment results, I should comment the line mentioned above, is that right? @proteus1991

Yes. You should not load my well-trained weights.

**Comment by proteus1991** [comment]
> After reading your [paper](https://xiaohongliu.ca/GridDehazeNet/resource/GridDehazeNet.pdf), I have some questions.
> 
> 1. Do u just use the ITS dataset to train the network and test on SOTS?
> 2. Do u just use the OTS dataset to train the network and test on SOTS?
> 3. If I use pretrained network (using OTS to train) to finetune on ITS, will I get better test results on SOTS?

For question 1 and 2, yes. I used ITS dataset to train the network and test on SOTS indoor and used OTS dataset for outdoor.

For question 3, I didn't train it in that way. You can read the paper which introduces RESIDE dataset for more details.

**Comment by leochangzliao** [comment]
> > After reading your [paper](https://xiaohongliu.ca/GridDehazeNet/resource/GridDehazeNet.pdf), I have some questions.
> > 
> > 1. Do u just use the ITS dataset to train the network and test on SOTS?
> > 2. Do u just use the OTS dataset to train the network and test on SOTS?
> > 3. If I use pretrained network (using OTS to train) to finetune on ITS, will I get better test results on SOTS?
> 
> For question 1 and 2, yes. I used ITS dataset to train the network and test on SOTS indoor and used OTS dataset for outdoor.
> 
> For question 3, I didn't train it in that way. You can read the paper which introduces RESIDE dataset for more details.

Thanks for ur reply!!! Great work!

**Comment by proteus1991** [comment]
> > > After reading your [paper](https://xiaohongliu.ca/GridDehazeNet/resource/GridDehazeNet.pdf), I have some questions.
> > > 
> > > 1. Do u just use the ITS dataset to train the network and test on SOTS?
> > > 2. Do u just use the OTS dataset to train the network and test on SOTS?
> > > 3. If I use pretrained network (using OTS to train) to finetune on ITS, will I get better test results on SOTS?
> > 
> > 
> > For question 1 and 2, yes. I used ITS dataset to train the network and test on SOTS indoor and used OTS dataset for outdoor.
> > For question 3, I didn't train it in that way. You can read the paper which introduces RESIDE dataset for more details.
> 
> Thanks for ur reply!!! Great work!

Thanks. This issue is closed.
