### ISSUE TITLE
How to use the own image data?

### ISSUE THREAD

**Issue by 0119tagawa** [proteus1991/GridDehazeNet#21]
I was impressive to see your great coding and tremendous results.
My question is how to use the our own image data to this model ?
I couldn't use them when the data are stored in the ./data/train/indoor/ and ./data/train/outdoor/.

**Comment by proteus1991** [comment]
Thanks for your interest. You can customize the `test.py` to run your own images on this model. More specifically, you can redirect to the image folder that stores those images.
