### ISSUE TITLE
trainlist.txt  some errors

### ISSUE THREAD

**Issue by aa12356jm** [proteus1991/GridDehazeNet#5]
hi，我按照使用说明下载好ITS和OTS的数据，并将对应文件夹放入指定目录，但是在读取图像数据的时候提示找不到trainlist.txt中的图像文件，经查看，ITS数据和OTS数据应该已经更新了，所以文件名都对应不上，不知道数据集更新了之后，还必须使用trainlist.txt文件中的过滤后的数据来训练吗？谢谢

**Comment by proteus1991** [comment]
你好, trainlist.txt清除了一些和RESIDE测试图相似的训练图,使结果更加公平. 如果此次更新已经清除了对应的图片,则不需要进一步清除了.
