### ISSUE TITLE
How can I test my hazy image?

### ISSUE THREAD

**Issue by wwlCape** [proteus1991/GridDehazeNet#6]
Hi, 
I have some hazy images, I want to de-haze these pictures by your method, what should I do? 
I am looking forward to your reply. Thanks a lot.

**Comment by proteus1991** [comment]
Hi,
If there is no clear (ground-truth) image for your hazy images, you need to slightly modify the ```text.py``` to feed only hazy images in GridDehazNet. Otherwise, just follow the steps in README to test your hazy images.

**Comment by wwlCape** [comment]
OK, thanks a lot !

**Comment by tkone2018** [comment]
@wwlCape 你好，请你你这个demo文件改好了吗？可以分享一下不
