### ISSUE TITLE
some issues about code

### ISSUE THREAD

**Issue by liang233** [proteus1991/GridDehazeNet#7]
hello, I have some  issues about code, 
![image](https://user-images.githubusercontent.com/8869756/71548867-682e2a80-29ef-11ea-84e6-6001aee362ad.png)

1.how do the parameter “output_size” work when the size of feature map  is odd?  by zero padding or other ways？
2. If zero padding is not added during training and zero padding needs to be added during testing, will there be performance degradation?

thanks

**Comment by proteus1991** [comment]
Hi, I will try to answer your questions as follows.

1. "output_size" is a parameter to give the exact output size you defined. To my understanding, it is similar to the "same" parameter in TensorFlow, which is achieved by zero padding as default.
2. I didn't test this case in detail. Intuitively, I believe there exists performance degradation, but it may be negligible.

If you have any other question, please let me know.
