### ISSUE TITLE
Feature addition with attention code question

### ISSUE THREAD

**Issue by Ikhwansong** [proteus1991/GridDehazeNet#9]
Hi, Nice to see you again! Thank you for your kind reply last.

I have a question about the line of code for feature addition with attention.

![image](https://user-images.githubusercontent.com/39337513/73592359-bed1db80-453c-11ea-8e4f-1cfa3353ecc5.png)

Is it different, compare of below ?

x_index[i,j] = self.rdb_module['{}_{}'.format(i, j-1)](x_index[i][j-1]) 
 + self.downsample_module['{}_{}'.format(i-1, j)](x_index[i-1][j])

It seems same operation.  

thank you

**Comment by proteus1991** [comment]
Your write-on code is the case while the attention is not used. 

Thanks,

Xiaohong
